import 'bootstrap'
//import '@/assets/bootstrap/3.3.7_fsm/js/bootstrap.min.js'
import 'bootstrap-select'
import 'bootstrap-select/dist/css/bootstrap-select.min.css'
//import 'bootstrap/dist/css/bootstrap.min.css'
import '@/assets/bootstrap/3.3.7_fsm/css/bootstrap.min.css'
